### ISSUE TITLE
Описание проекта

### ISSUE THREAD

**Issue by AndreyYuryev** [AndreyYuryev/skyCafe#5]
Проект для "визуализации" процессов в кафе - покупка товаров, в перспективе производство блюд выполнением оплаты и закупками.

**Comment by AndreyYuryev** [comment]
Цель проекта: создание архитектуры классов для описания процесса работы кафе.

**Comment by AndreyYuryev** [comment]
Получение информации от клиента - создание заказа - списание со склада - поставка

**Comment by AndreyYuryev** [comment]
![Image](https://github.com/AndreyYuryev/skyCafe/assets/58742343/a4b82649-939d-4afc-ac1a-7899ca0df14e)

**Comment by RikoshetGames** [comment]
Good

**Comment by AndreyYuryev** [comment]
Новая версия процесса


![Image](https://github.com/AndreyYuryev/skyCafe/assets/58742343/23737565-8a79-4f93-929f-0e5b28abb41f)
